### ISSUE TITLE
Clicking on red check mark icon in Grade Me block takes teacher to incorrect student

### ISSUE THREAD

**Issue by sulaganathan** [remotelearner/moodle-block_grade_me#10]
We have found that after the upgrade to Moodlerooms 3.0, when teachers click on the red check mark icon in Grade Me block for a submitted assignment they are taken to the incorrect student in the course. This is happening in all the courses we have checked. Can this issue be corrected?

Grade me version : 3.0.0.0 (2015102400)

Moodle version : 3.0

I believe someone has also reported the same issue, please advise if there is any fixes for that.

Thanks,
Srini

**Comment by sulaganathan** [comment]
Can someone check and update us?

**Comment by 2shediac** [comment]
Hi - we will be looking at the issue in the next week, and hope to have an
update available within a reasonable time period.

**Comment by sulaganathan** [comment]
Hi,

Did you get a chance to look into this? It would be great if you could give me ETA on fix/workaround, so that we can update our clients

**Comment by jamesmcq** [comment]
@sulaganathan We're working on something that should resolve this - current release schedule for this would be Aug 15-16.

**Comment by sulaganathan** [comment]
@jamesmcq thanks for the update..

**Comment by sulaganathan** [comment]
@jamesmcq Has the 3.0.0.1 have the fixes for this issue?

**Comment by sulaganathan** [comment]
@jamesmcq did you released any newer version on Aug 15-16? We are still waiting for fixes for this issue, Please let me know

**Comment by sulaganathan** [comment]
@jamesmcq  Please kindly look into this thread and update me at your convenience.. 

Thanks

**Comment by jamesmcq** [comment]
@sulaganathan Sorry for the delay - we have built the release and I'll be putting in up here later today. Thanks!

**Comment by sulaganathan** [comment]
@jamesmcq Thanks a lot for your update

**Comment by jamesmcq** [comment]
@sulaganathan I have just pushed the updated MOODLE_27_STABLE to MOODLE_31_STABLE branches - please take a look at the new release and let me know if it solves your issue. Thanks!
