### ISSUE TITLE
Support for Moodle 3.3/3.4

### ISSUE THREAD

**Issue by MC1171611** [remotelearner/moodle-block_grade_me#23]
Please forgive my forwardness, and my complete lack of understanding of the usage of GitHub, but I would like to reach out to the developers and ask if there's a plan to support Moodle 3.3 or 3.4 anytime soon. Grade Me was recommended to me by a project manager for an industrial Moodle application, and although my deployment is miniscule in comparison, I'm hoping to be able to use this plugin with a newer version of Moodle. Thank you.

**Comment by jamesmcq** [comment]
Hi @MC1171611 - Moodle 3.3 and 3.4 versions are now available in the MOODLE_33_STABLE and MOODLE_34_STABLE branches. Thanks!
