### ISSUE TITLE
I can't install last version con Moodle 3.10.4

### ISSUE THREAD

**Issue by cmartinb76** [remotelearner/moodle-block_grade_me#52]
I'm having trouble installing the last version ot this plugin (2021051700) on a Moodle 3.10.4
Our Moodle is running on a debian 10.10. We use docker for this Moodle.
Our DB is MariaDB 10.4.13

I have tryed the installation in the regular way from UI and here I have two options:
1. If I download the zip and upload it to the server (which is one of the ways as I was trying last week) then a validation error occurs when loading the .zip:
[OK] External module version [2021051700]
[Error] Moodle version required [2021051700]
2. If I install from the moodle extensions directory (by clicking that button) then it does install correctly but "tricking" the system a bit, modifying the moodle version in the list of my sites to 3.9, then it does install but the version 2020061502 (3.9.0.2) and not the latest one (3.11.0.0). If in the same way I modify the version of my moodle to 3.11 in the list of my sites, it also does not install the latest version of the plugin, appearing the same error as in the case of zip.

I have tryed to install also using moosh  and it returns the same message about incompatibility of versions.
Thanks.

**Comment by ghost** [comment]
Hello, The Moodle 3.11-compatible version of block_grade_me cannot be installed on a Moodle 3.10 site, as the requires version is too high and the values in version.php should never be manually changed.  For a M310 site you should install the latest Moodle 3.9-compatible version, and this will generally be the case with all plugins: if a release isn't available for your specific version of Moodle you can try using the _earlier_ version of the plugin but not a later one.
