### ISSUE TITLE
Grade-me Changes not saved

### ISSUE THREAD

**Issue by 2shediac** [remotelearner/moodle-block_grade_me#8]
This was reported by a user after updating to the latest version of Grade-me.

I have upgraded to the latest version and clicking on a submission now shows the correct submission as it used to.
However, this update issued a new problem, because for every assignment I try to grade through grade me, I get the following error:

The grade changes were NOT saved, as it was not possible to determine which submission they were for.

According to moodle, this is an error of the type: error/mod_assign/useridlistnotcached
If use the other method of going to the assignment, then manually find the correct submission and then grading it, the grading works as usual.

**Comment by KeironWalsh** [comment]
I'm having the same issue after upgrading to Moodle 2.9.6+ (Build: 20160520)

It's possible to grade the assignments by going directly to them, but as above using the Grade Me menu produces the error.

**Comment by jamesmcq** [comment]
This should now be resolved with the latest release for Moodle 2.7 - 3.1. Please open an issue if the issue persists. Thanks!
