### ISSUE TITLE
"Collapse/Expand All" string is harcoded 

### ISSUE THREAD

**Issue by s-cenni** [remotelearner/moodle-block_grade_me#9]
The string "Collapse/Expand All" is harcode so it can't be translated.

I think it would be useful to move the string into a variable and change the code in this way:

$expand = '<button class="btn btn-mini btn-primary" type="button" onclick="togglecollapseall();">**'.get_string('collapse_expand','block_grade_me').'**</button>';

Bye
Sara

**Comment by jamesmcq** [comment]
This should now be resolved in the latest version for Moodle 2.7 - 3.1. Thanks!
